### ISSUE TITLE
Tally server examples

### ISSUE THREAD

**Issue by matiaspl** [simonhyde/PiClock#1]
Is there any chance for a working "tally server" demonstrating more complex PiClock usage scenarios?

**Comment by simonhyde** [comment]
The working "tally server" that I have is written as part of my employer's internal control system, which I'm afraid I can't share. I will try to find some time to write an alternative, and some protocol documentation.

**Comment by matiaspl** [comment]
Any docs would be helpful. You C++ coding skills are astonishing but i find the code a bit hard to understand ;)

**Comment by simonhyde** [comment]
First bash at some protocol docs are in [TallyProtocol.md](../blob/master/TallyProtocol.md)

**Comment by peternewman** [comment]
See also https://github.com/simonhyde/PiClock/pull/3/files @matiaspl .

Did you write anything public @matiaspl ? I might need to write some stuff and would prefer to avoid reinventing the wheel if I can just hack at someone else's instead.

**Comment by peternewman** [comment]
@matiaspl a very, very slow reply, but I've now added an implementation to Bitfocus Companion, some details here https://github.com/simonhyde/PiClock/pull/14
