### ISSUE TITLE
Colour arguments in the protocol

### ISSUE THREAD

**Issue by peternewman** [simonhyde/PiClock#19]
In the general docs, it says a colour argument is:

> Hexadecimal representation of a 32-bit RGB in UTF-8/ASCII (basically the same format as HTML colours without the preceding #)

https://github.com/simonhyde/PiClock/blob/master/TallyProtocol.md#argument-format

But in SETLAYOUT, it has:

> Image name (already stored with STOREIMAGE) to use for the clock hand instead of a vector hand, or a colour code in the format '#000000' for the vector drawn hand. The hand must go up vertically in this image, with the centre of the image being the pivot point at the centre of the clockface.

It would be good if you just needed to send one implementation of colour. Maybe support the with hash version across the board, but keep without hash on the other arguments that used to support it for backwards compatibility or something? I can certainly see the benefit of a hash to differentiate from any other hex based image name (DEADBEEF etc).

Although equally STOREFONT and STOREIMAGE don't specify any requirements about the magic strings, but presumably they shouldn't have pipe, carriage return and hash in them (currently I could name my image #BADCAF...).

> Inline UTF-8 formatted string

**Comment by simonhyde** [comment]
> In the general docs, it says a colour argument is:
> 
> > Hexadecimal representation of a 32-bit RGB in UTF-8/ASCII (basically the same format as HTML colours without the preceding #)
> https://github.com/simonhyde/PiClock/blob/master/TallyProtocol.md#argument-format
> 
> But in SETLAYOUT, it has:
> 
> > Image name (already stored with STOREIMAGE) to use for the clock hand instead of a vector hand, or a colour code in the format '#000000' for the vector drawn hand. The hand must go up vertically in this image, with the centre of the image being the pivot point at the centre of the clockface.

This was a later addition, and required a # to clearly distinguish it from a font name

> It would be good if you just needed to send one implementation of colour. Maybe support the with hash version across the board, but keep without hash on the other arguments that used to support it for backwards compatibility or something? I can certainly see the benefit of a hash to differentiate from any other hex based image name (DEADBEEF etc).
not unreasonable, I'll look at that
> Although equally STOREFONT and STOREIMAGE don't specify any requirements about the magic strings, but presumably they shouldn't have pipe, carriage return and hash in them (currently I could name my image #BADCAF...).

Ha, yeah, I guess so 

> > Inline UTF-8 formatted string

**Comment by simonhyde** [comment]
Implemented as requested (but not tested!)

I haven't built new binaries or updated the images for https://github.com/simonhyde/pi-gen-piclock, but it will be in the next release
