### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by tvjon** [simonhyde/PiClock#6]
Thank you for the RPi 4 update.

I can't yet however, succeed in building it.

piclock.cpp: In member function ‘void DisplayBox::TextMid(const string&, const Fontinfo&, int, int, std::shared_ptr<std::__cxx11::basic_string<char> >)’:
piclock.cpp:507:6: error: ‘::TextClip’ has not been declared
    ::TextClip(x + m_corner, label_y,
      ^~~~~~~~
piclock.cpp:507:6: note: suggested alternative: ‘TextMid’
    ::TextClip(x + m_corner, label_y,
      ^~~~~~~~
      TextMid
piclock.cpp: In function ‘int main(int, char**)’:
piclock.cpp:1291:14: error: cannot convert ‘char**’ to ‘int*’
  init(&argc, argv, &iwidth, &iheight);     // Graphics initialization
              ^~~~
In file included from piclock.cpp:29:
openvg/shapes.h:31:26: note:   initializing argument 2 of ‘void init(int*, int*)’
  extern void init(int *, int *);
                          ^~~~~
piclock.cpp:1318:2: error: ‘MainLoop’ was not declared in this scope
  MainLoop(DrawFrame, KeyCallback);
  ^~~~~~~~

I can't find a definition for TextClip.

Thank you for any help.

**Comment by simonhyde** [comment]
hi tvjon,

It looks like you've only updated the PiClock repository, not the dependent submodules. In particular, it looks like you haven't got the right copy of the openvg repo, which should be defining TextClip, and a different version of the init() function.

Try running:
`git submodule update --init --recursive`

that should hopefully pull the correct version of all the submodules.

If that fails, you could try deleting your checkout and re-running a recursive clone.

**Comment by tvjon** [comment]
In fact, further on I had an incorrect version of ShivaVG, so your command line did the trick. 
Thank you Simon for your repo's; very useful learning tools. Hopefully with the help of your files, I can salvage some of my simple VG applications, that are currently useless on RPi 4.
